version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: timemanager_dev
      PGUSER: postgres
      PGPASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: timemanager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
