version: '3.8'

services:
  # web:
  #   build:
  #     context: ./clientTimeManager
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     MIX_ENV: dev
  #     PGDATABASE: ${DATABASE_NAME}
  #     PGUSER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #    env_file:
  #      - .env
  #   depends_on:
  #     - postgres-service

  api:
    build:
      context: ./apiTimemanager
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PGDATABASE: ${DATABASE_NAME}
      PGUSER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env

  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
