version: '3.8'

services:
  # web:
  #   build:
  #     context: ./clientTimeManager
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     MIX_ENV: dev
  #     PGDATABASE: timemanager_dev
  #     PGUSER: postgres
  #     PGPASSWORD: postgres
  #   depends_on:
  #     - postgres-service

  api:
    build:
      context: ./apiTimemanager
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PGDATABASE: timemanager_dev
      PGUSER: postgres
      PGPASSWORD: postgres
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:16
    environment:
      POSTGRES_DB: timemanager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
