version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PGDATABASE: timemanager_dev
      PGUSER: postgres
      PGPASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: timemanager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
