name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker Containers
        run: |
          # Build and run containers using docker-compose
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml up -d

      - name: Check Containers Status
        run: |
          # Check the status of containers (optional)
          docker-compose -f docker-compose.yaml ps

      - name: Run Tests (if applicable)
        run: |
          # If you have tests to run inside the containers, you can run them here
          # For example: docker-compose -f docker-compose.yml exec your-service-name pytest

      - name: Stop Containers (if needed)
        run: |
          # If you need to stop and remove the containers
          docker-compose -f docker-compose.yaml down

  mirror:
    name: Push content of the current repo on mirror
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.5.1
      with:
        REMOTE: git@github.com:tistech0/GoTime.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
        DEBUG: "true"
