name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker Containers
        run: |
          # Build and run containers using docker-compose
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml up -d

      - name: Check Containers Status
        run: |
          # Check the status of containers
          docker-compose -f docker-compose.yaml ps

      - name: Run Tests (if applicable)
        run: |
          # If you have tests to run inside the containers, you can run them here
          # For example: docker-compose -f docker-compose.yml exec your-service-name pytest

      - name: Stop Containers (if needed)
        run: |
          # If you need to stop and remove the containers
          docker-compose -f docker-compose.yaml down

  sonarQube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: [build]
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_api_image:
    name: Build and Push Docker Image for apiTimeManager
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: gotime-403610

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          cd apiTimemanager
          docker build -t eu.gcr.io/gotime-403610/gotime-api:latest .
          docker push eu.gcr.io/gotime-403610/gotime-api:latest

  mirror:
    name: Push content of the current repo on mirror
    runs-on: ubuntu-latest
    needs: [sonarQube, build_api_image]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2025/T-POO-700-NAN_9.git
          ssh_private_key: ${{ secrets.SSH_KEY }}

